# Generated by Django 2.0.13 on 2019-12-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_points'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0020_auto_20191209_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imagesets', models.ManyToManyField(to='images.ImageSet')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'team')},
        ),
    ]
