# Generated by Django 2.0.13 on 2019-12-03 12:32

from django.db import migrations, models
from openslide import OpenSlide
import openslide
from django.conf import settings
import os


def set_mpp_and_power(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Images = apps.get_model('images', 'Image')
    for image in Images.objects.using(db_alias).all():
        try:
            path = os.path.join(settings.IMAGE_PATH, image.image_set.path, image.filename)
            slide = OpenSlide(path)

            try:
                mpp_x = slide.properties[openslide.PROPERTY_NAME_MPP_X]
                mpp_y = slide.properties[openslide.PROPERTY_NAME_MPP_Y]
                image.mpp = (float(mpp_x) + float(mpp_y)) / 2
            except:
                image.mpp = 0
            try:
                image.objectivePower = slide.properties[openslide.PROPERTY_NAME_OBJECTIVE_POWER]
            except:
                image.objectivePower = 1

            image.save(using=db_alias)
        except:
            continue



class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_imageset_zip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='mpp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='objectivePower',
            field=models.FloatField(default=1),
        ),
        migrations.RunPython(set_mpp_and_power)
    ]
