# Generated by Django 2.0.13 on 2019-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_auto_20191203_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='collaboration_type',
            field=models.IntegerField(choices=[(0, 'Collaborative'), (1, 'Competitive'), (2, 'SecondOpinion')], default=0),
        ),
    ]
