# Generated by Django 2.0.13 on 2019-12-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_imageset_collaboration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
