version: '3.7'

services:
  web:
    build: ./imagetagger
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./imagetagger/:/usr/src/imagetagger/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
        - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env.dev.db

volumes:
  postgres_data:      