version: '3.7'

services:
  web:
    build: 
        context: ./exact
        dockerfile: Dockerfile.iSyntax    
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./exact/:/usr/src/exact/
    ports:
      - 8000:8000
      - 3001:3001
    env_file:
      - ./env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
        - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env.dev.db

volumes:
  postgres_data:      