# Generated by Django 3.2.11 on 2023-01-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220103_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='frontend',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Lightroom')], default=1),
        ),
    ]
