# Generated by Django 3.2.11 on 2023-01-09 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_frontend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='frontend',
        ),
        migrations.CreateModel(
            name='UI_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend', models.IntegerField(choices=[(1, 'Default'), (2, 'Lightroom')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
