# Generated by Django 4.2.18 on 2025-12-23 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_personalaccesstoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UI_User",
            new_name="UserPreferences",
        ),
    ]
