# Generated by Django 4.2.18 on 2025-12-23 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userpreferences_delete_ui_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='frontend',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Lightroom')], default=2),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prefs', to=settings.AUTH_USER_MODEL),
        ),
    ]
