# Generated by Django 4.2.18 on 2026-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userpreferences_is_site_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='frontend',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Lightroom'), (3, 'Lightroom v2')], default=2),
        ),
    ]
