# Generated by Django 3.2.4 on 2022-01-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_auto_20220103_1602'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagesets',
            field=models.ManyToManyField(blank=True, to='images.ImageSet'),
        ),
    ]
