# Generated by Django 3.2.11 on 2022-12-30 18:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exact.processing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0030_auto_20220103_1602'),
        ('annotations', '0048_auto_20220103_1610'),
        ('administration', '0002_auto_20220103_1602'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('contact', models.EmailField(max_length=80)),
                ('abouturl', models.URLField(max_length=80)),
                ('icon', models.ImageField(upload_to=exact.processing.models.plugins_directory)),
                ('products', models.ManyToManyField(related_name='plugins', to='administration.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PluginJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processing_complete', models.FloatField(default=0.0)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now)),
                ('eta_time', models.DateTimeField(default=datetime.datetime.now)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluginJobs', to='images.image')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='processing.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='PluginResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('completed_time', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pluginResults', to='images.image')),
                ('job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='processing.pluginjob')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='processing.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='PluginResultEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('pluginresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='processing.pluginresult')),
            ],
        ),
        migrations.CreateModel(
            name='PluginResultBitmap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('scale_min', models.FloatField(default=0)),
                ('scale_max', models.FloatField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('default_threshold', models.FloatField(default=0)),
                ('default_alpha', models.FloatField(default=1)),
                ('channels', models.IntegerField(default=1)),
                ('transformation_matrix', models.JSONField(null=True)),
                ('meta_data', models.JSONField(null=True)),
                ('bitmap', models.FileField(upload_to=exact.processing.models.plugin_bitmap_directory)),
                ('pluginresultentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitmap_results', to='processing.pluginresultentry')),
            ],
        ),
        migrations.CreateModel(
            name='PluginResultAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vector', models.JSONField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(null=True)),
                ('annotationtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotations.annotationtype')),
                ('pluginresultentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_results', to='processing.pluginresultentry')),
            ],
        ),
    ]
