# Generated by Django 3.2.11 on 2023-01-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plugin',
            options={'permissions': [('use_server_side_plugins', 'User can use server-side plugins')]},
        ),
        migrations.AlterModelOptions(
            name='pluginresult',
            options={'permissions': [('delete_plugin_results', 'User can delete plugin results')]},
        ),
        migrations.RemoveField(
            model_name='pluginresultbitmap',
            name='question_text',
        ),
    ]
