# Generated by Django 3.2.11 on 2023-01-01 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_auto_20230101_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginresultannotation',
            old_name='annotationtype',
            new_name='annotation_type',
        ),
        migrations.AddField(
            model_name='pluginresultannotation',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pluginresultannotation',
            name='unique_identifier',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
