# Generated by Django 3.2.11 on 2023-01-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_auto_20220103_1602'),
        ('processing', '0003_auto_20230101_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginresultannotation',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pluginresultbitmap',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
    ]
