# Generated by Django 3.2.11 on 2023-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_auto_20230101_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='package',
            field=models.CharField(default='', max_length=200),
        ),
    ]
