# Generated by Django 3.2.11 on 2023-01-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_plugin_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginjob',
            name='error_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pluginjob',
            name='error_message',
            field=models.TextField(null=True),
        ),
    ]
