# Generated by Django 3.2.11 on 2023-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_auto_20230105_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginjob',
            name='attached_worker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
