# Generated by Django 3.2.11 on 2023-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_auto_20230117_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginresult',
            name='default_alpha',
            field=models.FloatField(default=1.0),
        ),
    ]
