# Generated by Django 3.2.11 on 2023-03-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20220103_1602'),
        ('processing', '0010_pluginresult_default_alpha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='plugins', to='administration.Product'),
        ),
        migrations.AlterField(
            model_name='pluginresult',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='processing.pluginjob'),
        ),
    ]
