# Generated by Django 3.2.11 on 2023-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0011_auto_20230306_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginresultannotation',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
    ]
