# Generated by Django 3.2.11 on 2023-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0012_pluginresultannotation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginresultentry',
            name='default_threshold',
            field=models.FloatField(default=0.0),
        ),
    ]
