# Generated by Django 4.2.11 on 2024-10-01 21:43

from django.db import migrations, models
import exact.processing.models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_pluginresultentry_default_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginresultbitmap',
            name='location_rect',
            field=models.JSONField(default=exact.processing.models.default_rect, null=True),
        ),
    ]
