# Generated by Django 2.0.13 on 2019-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0028_annotationtype_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='default_height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='default_width',
            field=models.IntegerField(default=50),
        ),
    ]
