# Generated by Django 2.0.13 on 2019-12-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0031_auto_20191205_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='image_file',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
