# Generated by Django 2.0.13 on 2019-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0034_auto_20191211_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='area_hit_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
