# Generated by Django 2.0.13 on 2019-12-12 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagetagger.annotations.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0020_auto_20191209_1341'),
        ('annotations', '0035_auto_20191211_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(default=1)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
