# Generated by Django 2.0.13 on 2019-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0036_logimageaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='logimageaction',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
