# Generated by Django 3.0 on 2020-01-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_auto_20191231_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Server Generated'), (2, 'File Link Generated')], default=0),
        ),
    ]
