# Generated by Django 3.0 on 2020-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_image_image_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='path',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
