# Generated by Django 3.0 on 2020-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_auto_20200403_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('imagesets', models.ManyToManyField(related_name='set_versions', to='images.ImageSet')),
            ],
        ),
    ]
