# Generated by Django 3.0 on 2020-05-01 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_setversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='setversion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
