# Generated by Django 3.1.4 on 2021-03-04 15:30

from django.db import migrations, models
import django.db.models.deletion
import exact.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_auto_20200611_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningmode',
            name='screening_tiles',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='ImageRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation_matrix', models.JSONField(null=True)),
                ('registration_error', models.FloatField(default=-1)),
                ('runtime', models.IntegerField(default=-1)),
                ('file', models.FileField(null=True, upload_to=exact.images.models.version_directory_path)),
                ('source_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_image', to='images.image')),
                ('target_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_image', to='images.image')),
            ],
            options={
                'unique_together': {('source_image', 'target_image')},
            },
        ),
    ]
