# Generated by Django 3.2.4 on 2022-01-03 16:02

from django.db import migrations, models
import exact.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_auto_20210304_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='show_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageregistration',
            name='file',
            field=models.FileField(null=True, upload_to=exact.images.models.registration_directory_path),
        ),
        migrations.AlterField(
            model_name='imageregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='screeningmode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='settag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
