# Generated by Django 4.2.3 on 2023-07-24 07:18

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
            ('images', '0030_auto_20220103_1602'),
        ]

# Add all necessary frames for the existing images
def add_default_frames(apps, schema_editor):
    FrameDescription = apps.get_model('images', 'FrameDescription')
    Image = apps.get_model('images','Image')

    # fetch all objects
    images = Image.objects.all()

    for image in images:
        for frame in range(image.frames):
            FrameDescription.objects.create(
                Image=image,
                frame_id=frame
            )



class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_auto_20220103_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='defaultFrame',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FrameDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.IntegerField(choices=[(0, 'z Stack'), (1, 'time series'), (255, 'undefined')], default=0)),
                ('descreption', models.CharField(default='')),
                ('frame_id', models.IntegerField(default=0)),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FrameDescriptions', to='images.image')),
            ],
        ),
        migrations.RunPython(add_default_frames),
    ]
