# Generated by Django 4.2.3 on 2023-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0031_image_defaultframe_framedescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framedescription',
            old_name='descreption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='framedescription',
            name='file_path',
            field=models.CharField(default=''),
        ),
    ]
