# Generated by Django 4.2.11 on 2024-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0033_image_stack_setfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedescription',
            name='description',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='framedescription',
            name='file_path',
            field=models.CharField(default='', max_length=320),
        ),
    ]
