# Generated by Django 4.2.18 on 2025-01-21 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0034_alter_framedescription_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('filesize', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('associated_to_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('image_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_files', to='images.imageset')),
            ],
        ),
    ]
