# Generated by Django 4.2.18 on 2025-04-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0035_auxiliaryfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageregistration',
            name='registration_points',
            field=models.JSONField(null=True),
        ),
    ]
