# Generated by Django 4.2.18 on 2026-04-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0036_imageregistration_registration_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageset',
            name='show_registration',
        ),
    ]
