# Generated by Django 2.0.13 on 2019-10-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181114_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='color_code',
            field=models.CharField(default='#CC4444', max_length=7),
        ),
    ]
