# Generated by Django 2.0.13 on 2019-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0030_annotationtype_sort_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='closed',
            new_name='deleted',
        ),
        migrations.AddField(
            model_name='annotation',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='closed',
            field=models.BooleanField(default=True),
        ),
    ]
