# Generated by Django 2.0.13 on 2019-12-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('annotations', '0032_annotationtype_imagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Product'),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
