# Generated by Django 2.0.13 on 2019-12-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('annotations', '0033_auto_20191211_0946'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationtype',
            unique_together={('name', 'product')},
        ),
    ]
