# Generated by Django 3.0 on 2020-02-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_image_image_type'),
        ('annotations', '0038_annotation_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logimageaction',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
