# Generated by Django 3.0 on 2020-03-15 13:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0039_auto_20200218_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
