# Generated by Django 3.0 on 2020-04-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0040_annotation_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
