# Generated by Django 3.0 on 2020-04-09 11:07

from django.db import migrations, models
import django.db.models.deletion
import exact.annotations.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0041_auto_20200403_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationMediaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to=exact.annotations.models.annotation_directory_path)),
                ('media_file_type', models.IntegerField(default=exact.annotations.models.AnnotationMediaFile.MediaFileType['Image'])),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media_files', related_query_name='uploaded_media_file', to='annotations.Annotation')),
            ],
            options={
                'unique_together': {('name', 'annotation')},
            },
        ),
    ]
