# Generated by Django 3.0 on 2020-06-11 07:58

from django.db import migrations
import exact.annotations.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0044_auto_20200501_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportformat',
            name='annotation_format',
            field=exact.annotations.fields.NonStrippingTextField(default='%%imagename|%%type|{%%vector}|'),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='base_format',
            field=exact.annotations.fields.NonStrippingTextField(default='%%content'),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='not_in_image_format',
            field=exact.annotations.fields.NonStrippingTextField(default='image name|annotation type|not in image'),
        ),
        migrations.AlterField(
            model_name='exportformat',
            name='vector_format',
            field=exact.annotations.fields.NonStrippingTextField(default='"x%%count1": %%x,"y%%count1": %%y,'),
        ),
    ]
