# Generated by Django 3.1.4 on 2021-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0045_auto_20200611_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='vector',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='annotationversion',
            name='vector',
            field=models.JSONField(null=True),
        ),
    ]
