# Generated by Django 3.2.4 on 2022-01-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0046_auto_20210304_1530'),
    ]

    migrations.RunSQL('''
        DROP FUNCTION IF EXISTS update_points();
        DROP TRIGGER IF EXISTS points_update ON annotations_verification;
        ''')
