# Generated by Django 4.2.18 on 2025-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0049_annotationtype_multi_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='drawing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='inspection_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='num_points',
            field=models.IntegerField(default=0),
        ),
    ]
