# Generated by Django 4.2.18 on 2026-05-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0049_annotationtype_multi_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('tile_x', models.IntegerField()),
                ('tile_y', models.IntegerField()),
                ('frame', models.IntegerField(default=0)),
                ('data', models.BinaryField()),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_tiles', to='annotations.annotation')),
            ],
            options={
                'indexes': [models.Index(fields=['annotation', 'level', 'frame'], name='annotations_annotat_9dba0a_idx')],
                'unique_together': {('annotation', 'level', 'tile_x', 'tile_y', 'frame')},
            },
        ),
    ]
