# Generated by Django 4.2.18 on 2025-10-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0050_annotation_drawing_time_annotation_inspection_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_annotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
