# Generated by Django 4.2.18 on 2025-10-19 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotations', '0051_annotation_locked_annotation_locked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
